version: '3.7'
 
services: 
  postgresdb:
    image: postgres:latest
    container_name: postgresdb
    ports: 
      - "5432:5432"
    environment: 
      POSTGRES_DB: studentmanagment
      POSTGRES_PASSWORD: '123456'
      PG_DATA: var/lib/postgresql/data
 
  pgadmin:
    image: dpage/pgadmin4
    ports: 
      - 5433:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=dev@test.mail
      - PGADMIN_DEFAULT_PASSWORD=123 
       
  studentservicec:
    image: studentservice
    container_name: studentservicec
    ports:
      - 3000:3000
    command: npm run start:prod
    depends_on:
      - postgresdb

  sutudentservicef:
    image: studentservicefrontnew
    container_name: sutudentservicef
    ports:
      - 4200:4200
    command: > 
      bash -c "npm install && ng serve --host 0.0.0.0 --port 4200"
    depends_on:
      - studentservicec
  
 
